name: Validate CitSci Notebooks Against Flake8

on:
  push:
    branches:
       - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'main'

jobs:
  validate:
    name: Validate notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Create config file
      #   run: |
      #     echo "[flake8]" >> ~/.config/flake8
      #     echo "max-line-length = 99" >> ~/.config/flake8
      #     echo "ignore = E133, E226, E228, E266, N802, N803, N806, N812, N813, N815, N816, W503" >> ~/.config/flake8
      #     cat ~/.config/flake8

      - name: Run Flake8 validation
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          use-pylint: false
          use-pycodestyle: false