name: Validate CitSci Notebooks Against Flake8

on:
  push:
    branches:
       - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'main'

jobs:
  validate:
    name: Validate notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Flake8 validation
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          use-pylint: false
          use-pycodestyle: false

      - name: Validation notebooks
        run: flake8 *.ipynb