name: Validate

on:
  push:
    branches:
       - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'main'

#jobs:
#  flake8:
#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v4
#    - uses: mhitza/flake8-jupyter-notebook@v1

jobs:
  validate-notebooks:
    name: Notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # changed from v3 to v4

      - name: Validate notebooks
        uses: mhitza/flake8-jupyter-notebook@v1.2
            
  validate-py-scripts:
    name: Py Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate utils.py
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          use-pylint: false
          use-pycodestyle: false