name: Validate CitSci Notebooks Against Flake8

on:
  push:
    branches:
       - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'main'

jobs:
  validate-notebooks:
    name: Validate notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quick github.head_ref test
        run: echo ${{github.head_ref}}

      - name: Validate notebooks
        uses: mhitza/flake8-jupyter-notebook@v1.1
            
  validate-py-scripts:
    name: Validate py scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate utils.py
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          use-pylint: false
          use-pycodestyle: false